# ============================================================================
# Native zsh completion
# Generated by suitup
# ============================================================================

autoload -Uz compinit

_zsh_compdump_file="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/.zcompdump"
typeset -g _zsh_completion_cache_mode='refresh'

if [[ -s "$_zsh_compdump_file" && -n "$(command find "$_zsh_compdump_file" -mtime -7 -print 2>/dev/null)" ]]; then
  _zsh_completion_cache_mode='cache-hit'
  compinit -C -d "$_zsh_compdump_file"
else
  compinit -d "$_zsh_compdump_file"
fi

bindkey -M emacs '^I' expand-or-complete
bindkey -M viins '^I' expand-or-complete
bindkey -M vicmd '^I' expand-or-complete
