# ============================================================================
# zinit plugin declarations
# Generated by suitup
# ============================================================================

zinit ice wait"0" lucid atload'_zsh_autosuggest_bind_widgets'
zinit light 'zsh-users/zsh-autosuggestions'

zinit ice wait"0" lucid
zinit light 'zsh-users/zsh-syntax-highlighting'

zinit ice depth"1"
zinit light romkatv/powerlevel10k
