# ============================================================================
# Prompt / theme loading — must run last
# Generated by suitup (Powerlevel10k preset)
# ============================================================================

if [[ -f ~/.p10k.zsh ]]; then
  # For zinit-based setups: load p10k as the final plugin so it wraps everything
  (( ${+functions[zinit]} )) && { zinit ice depth"1"; zinit light romkatv/powerlevel10k; }

  source ~/.p10k.zsh
else
  PROMPT='%F{cyan}%n@%m%f:%F{yellow}%~%f %# '
  RPROMPT=
fi
