# ============================================================================
# Prompt / theme loading — must run last
# Generated by suitup (Powerlevel10k preset)
# ============================================================================

if (( ${+functions[zinit]} )); then
  # Load p10k last so it wraps everything and exposes the `p10k` command.
  zinit ice depth"1"
  zinit light romkatv/powerlevel10k
fi

if [[ -f ~/.p10k.zsh ]]; then
  source ~/.p10k.zsh
else
  PROMPT='%F{cyan}%n@%m%f:%F{yellow}%~%f %# '
  RPROMPT=
fi
