# ============================================================================
# Prompt / theme loading — must run last
# Generated by suitup (Powerlevel10k preset)
# ============================================================================

if [[ -f ~/.p10k.zsh ]]; then
  source ~/.p10k.zsh
else
  PROMPT='%F{cyan}%n@%m%f:%F{yellow}%~%f %# '
  RPROMPT=
fi
