# ============================================================================
# Prompt / theme loading — must run last
# Generated by suitup (basic preset)
# ============================================================================

PROMPT='%F{cyan}%n@%m%f:%F{yellow}%~%f %# '
RPROMPT=
