import { describe, test, expect, vi, beforeEach, afterEach } from "vitest";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { createSandbox } from "./helpers.js";

const { mockConfirm, mockInfo, mockWarn, mockSuccess } = vi.hoisted(() => ({
  mockConfirm: vi.fn(),
  mockInfo: vi.fn(),
  mockWarn: vi.fn(),
  mockSuccess: vi.fn(),
}));

vi.mock("@clack/prompts", () => ({
  log: { success: mockSuccess, step: vi.fn(), info: mockInfo, warn: mockWarn, error: vi.fn() },
  confirm: mockConfirm,
  isCancel: vi.fn(() => false),
}));

import { applyManagedConfigUpdate, mergeLineAdditions, renderUnifiedDiff } from "../src/utils/config-diff.js";
import { redactAliasValues } from "../src/steps/aliases.js";

function stripAnsiCodes(line) {
  return line.replace(/\u001b\[[0-9;]*m/g, "");
}

describe("managed config diff updates", () => {
  let sandbox;
  let source;
  let dest;

  beforeEach(() => {
    vi.clearAllMocks();
    sandbox = createSandbox();
    mkdirSync(join(sandbox.path, "configs"), { recursive: true });
    mkdirSync(join(sandbox.path, "home", ".config", "zsh", "shared"), { recursive: true });
    source = join(sandbox.path, "configs", "aliases.zsh");
    dest = join(sandbox.path, "home", ".config", "zsh", "shared", "aliases.zsh");
  });

  afterEach(() => {
    sandbox.cleanup();
  });

  test("given user edits between suitup lines, when a shipped line is added, then the merge preserves user edits and previews a diff", async () => {
    writeFileSync(source, [
      "# Generated by suitup",
      "# suitup comment xxx",
      "alias boo=''",
      "alias foo=''",
      "",
      "# suitup comment yyy",
      "alias zoo=''",
      "",
    ].join("\n"), "utf-8");
    writeFileSync(dest, [
      "# Generated by suitup",
      "# suitup comment xxx",
      "alias boo=''",
      "",
      "# comment",
      "alias goo=''",
      "",
      "# suitup comment yyy",
      "alias zoo=''",
      "",
    ].join("\n"), "utf-8");
    mockConfirm.mockResolvedValue(true);

    const result = await applyManagedConfigUpdate({ source, dest, label: "aliases", home: join(sandbox.path, "home") });

    expect(result).toEqual({ changed: true, reason: "updated" });
    const written = readFileSync(dest, "utf-8");
    expect(written).toContain("alias foo=''\n\n# comment\nalias goo=''");
    expect(written).toContain("# suitup comment yyy\nalias zoo=''");
    expect(mockInfo.mock.calls.map((call) => call[0]).join("\n")).toContain("+ alias foo=''");
  });

  test("given a diff preview, when the user declines, then the existing file is left untouched", async () => {
    const shipped = "# Generated by suitup\nalias boo=''\nalias foo=''\n";
    const existing = "# Generated by suitup\nalias boo=''\n# user\nalias goo=''\n";
    writeFileSync(source, shipped, "utf-8");
    writeFileSync(dest, existing, "utf-8");
    mockConfirm.mockResolvedValue(false);

    const result = await applyManagedConfigUpdate({ source, dest, label: "aliases", home: join(sandbox.path, "home") });

    expect(result).toEqual({ changed: false, reason: "declined" });
    expect(readFileSync(dest, "utf-8")).toBe(existing);
    expect(mockWarn).toHaveBeenCalledWith("Skipped aliases; user changes were preserved.");
  });

  test("redacts alias values from managed diff previews", async () => {
    writeFileSync(source, "# Generated by suitup\nalias safe='echo safe'\nalias added='echo added'\n", "utf-8");
    writeFileSync(dest, "# Generated by suitup\nalias safe='TOKEN=secret command'\n", "utf-8");
    mockConfirm.mockResolvedValue(false);

    await applyManagedConfigUpdate({
      source,
      dest,
      label: "aliases",
      home: join(sandbox.path, "home"),
      redactPreview: redactAliasValues,
    });

    const preview = mockInfo.mock.calls.map((call) => call[0]).join("\n");
    expect(preview).toContain("alias added=<redacted>");
    expect(preview).not.toContain("TOKEN");
    expect(preview).not.toContain("secret");
  });

  test("given an unmarked local config, when suitup has additions, then the file is skipped with a reason", async () => {
    const unmarkedContent = "# my aliases\nalias mine=''\n";
    writeFileSync(source, "# Generated by suitup\nalias boo=''\n", "utf-8");
    writeFileSync(dest, unmarkedContent, "utf-8");

    const result = await applyManagedConfigUpdate({ source, dest, label: "aliases", home: join(sandbox.path, "home") });

    expect(result).toEqual({ changed: false, reason: "unsupported" });
    expect(readFileSync(dest, "utf-8")).toBe(unmarkedContent);
    expect(mockConfirm).not.toHaveBeenCalled();
    expect(mockInfo.mock.calls.map((call) => call[0]).join("\n")).toMatch(/Skipped aliases: .*user-owned config/);
  });

  test("given existing and shipped content, mergeLineAdditions only adds shipped lines and does not remove local lines", () => {
    const merged = mergeLineAdditions("a\nlocal\nc\n", "a\nb\nc\n");

    expect(merged).toBe("a\nb\nlocal\nc\n");
  });

  test("given before and after content, renderUnifiedDiff shows additions and removals", () => {
    const diff = renderUnifiedDiff("a\nold\n", "a\nnew\n", { from: "before", to: "after" });

    expect(diff.split("\n").map(stripAnsiCodes)).toEqual([
      "--- before",
      "+++ after",
      "  a",
      "- old",
      "+ new",
    ]);
  });
});
