import { describe, test, expect, vi, beforeEach, afterEach } from "vitest";
import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { createSandbox } from "./helpers.js";

const { mockConfirm } = vi.hoisted(() => ({
  mockConfirm: vi.fn(),
}));

vi.mock("@clack/prompts", () => ({
  log: { success: vi.fn(), step: vi.fn(), info: vi.fn(), warn: vi.fn(), error: vi.fn() },
  spinner: vi.fn(() => ({ start: vi.fn(), stop: vi.fn() })),
  confirm: mockConfirm,
  text: vi.fn(),
  isCancel: vi.fn(() => false),
}));

import { backupShellRcFiles, setupZshConfig, writeZshrc } from "../src/steps/zsh-config.js";
import { setupAliases } from "../src/steps/aliases.js";
import { setupVim } from "../src/steps/vim.js";

describe("zsh-config step", () => {
  let sandbox;

  beforeEach(() => {
    vi.clearAllMocks();
    sandbox = createSandbox();
  });

  afterEach(() => {
    sandbox.cleanup();
  });

  test("creates full directory structure in empty sandbox", async () => {
    await setupZshConfig({ home: sandbox.path });

    expect(existsSync(join(sandbox.path, ".config", "zsh", "core", "perf.zsh"))).toBe(true);
    expect(existsSync(join(sandbox.path, ".config", "zsh", "core", "env.zsh"))).toBe(true);
    expect(existsSync(join(sandbox.path, ".config", "zsh", "core", "paths.zsh"))).toBe(true);
    expect(existsSync(join(sandbox.path, ".config", "zsh", "core", "options.zsh"))).toBe(true);
    expect(existsSync(join(sandbox.path, ".config", "zsh", "shared", "tools.zsh"))).toBe(true);
    expect(existsSync(join(sandbox.path, ".config", "zsh", "shared", "fzf.zsh"))).toBe(true);
    expect(existsSync(join(sandbox.path, ".config", "zsh", "shared", "prompt.zsh"))).toBe(true);
    expect(existsSync(join(sandbox.path, ".config", "zsh", "local", "machine.zsh"))).toBe(true);
  });

  test("copies the optimized startup config files", async () => {
    await setupZshConfig({ home: sandbox.path });

    const perf = readFileSync(join(sandbox.path, ".config", "zsh", "core", "perf.zsh"), "utf-8");
    const tools = readFileSync(join(sandbox.path, ".config", "zsh", "shared", "tools.zsh"), "utf-8");
    const fzf = readFileSync(join(sandbox.path, ".config", "zsh", "shared", "fzf.zsh"), "utf-8");

    expect(perf).toContain("EPOCHREALTIME");
    expect(perf).toContain("_record_stage_duration");
    expect(tools).toContain("_source_cached_tool_init");
    expect(tools).toContain("$_zsh_tools_cache_dir");
    expect(fzf).toContain("FZF_DEFAULT_COMMAND");
    expect(fzf).toContain("FZF_CTRL_T_OPTS");
  });

  test("writes a basic prompt preset when selected", async () => {
    await setupZshConfig({ home: sandbox.path, promptTheme: "basic" });

    const prompt = readFileSync(join(sandbox.path, ".config", "zsh", "shared", "prompt.zsh"), "utf-8");
    expect(prompt).toContain("basic preset");
    expect(prompt).not.toContain("powerlevel10k");
  });

  test("skips existing config files without overwriting", async () => {
    // Pre-create a core file with custom content
    mkdirSync(join(sandbox.path, ".config", "zsh", "core"), { recursive: true });
    writeFileSync(join(sandbox.path, ".config", "zsh", "core", "env.zsh"), "# my custom env", "utf-8");

    await setupZshConfig({ home: sandbox.path });

    // env.zsh should retain custom content
    const content = readFileSync(join(sandbox.path, ".config", "zsh", "core", "env.zsh"), "utf-8");
    expect(content).toBe("# my custom env");

    // Other files should still be created
    expect(existsSync(join(sandbox.path, ".config", "zsh", "core", "perf.zsh"))).toBe(true);
  });

  test("writeZshrc creates .zshrc in empty sandbox", async () => {
    await writeZshrc("zinit", { home: sandbox.path });

    expect(existsSync(join(sandbox.path, ".zshrc"))).toBe(true);
    const content = readFileSync(join(sandbox.path, ".zshrc"), "utf-8");
    expect(content).toContain("ZSH_CONFIG");
  });

  test("writeZshrc overwrites suitup-managed .zshrc without asking", async () => {
    writeFileSync(join(sandbox.path, ".zshrc"), "# Generated by suitup\nold content", "utf-8");

    await writeZshrc("zinit", { home: sandbox.path });

    const content = readFileSync(join(sandbox.path, ".zshrc"), "utf-8");
    expect(content).not.toContain("old content");
    expect(content).toContain("ZSH_CONFIG");
    expect(mockConfirm).not.toHaveBeenCalled();
  });

  test("writeZshrc asks before overwriting non-suitup .zshrc", async () => {
    writeFileSync(join(sandbox.path, ".zshrc"), "# my custom zshrc\nexport FOO=bar", "utf-8");
    mockConfirm.mockResolvedValue(false);

    await writeZshrc("zinit", { home: sandbox.path });

    expect(mockConfirm).toHaveBeenCalled();
    // Since user declined, original content preserved
    const content = readFileSync(join(sandbox.path, ".zshrc"), "utf-8");
    expect(content).toContain("FOO=bar");
  });

  test("writeZshrc creates backup when user confirms overwrite", async () => {
    writeFileSync(join(sandbox.path, ".zshrc"), "# my custom zshrc\nexport FOO=bar", "utf-8");
    mockConfirm.mockResolvedValue(true);

    await writeZshrc("zinit", { home: sandbox.path });

    // New content should be the template
    const content = readFileSync(join(sandbox.path, ".zshrc"), "utf-8");
    expect(content).toContain("ZSH_CONFIG");

    const backupRoot = join(sandbox.path, ".config", "suitup", "backups");
    const backupDirs = readdirSync(backupRoot);
    expect(backupDirs.length).toBe(1);

    const backupDir = join(backupRoot, backupDirs[0]);
    expect(existsSync(join(backupDir, ".zshrc"))).toBe(true);
    expect(readFileSync(join(backupDir, ".zshrc"), "utf-8")).toContain("FOO=bar");
    expect(existsSync(join(backupDir, "manifest.json"))).toBe(true);
  });

  test("backupShellRcFiles stores existing shell rc files under suitup backups", async () => {
    writeFileSync(join(sandbox.path, ".zshrc"), "export ZSH_TEST=1\n", "utf-8");
    writeFileSync(join(sandbox.path, ".bashrc"), "export BASH_TEST=1\n", "utf-8");

    const result = await backupShellRcFiles({ home: sandbox.path, reason: "setup" });

    expect(result.files).toEqual([".zshrc", ".bashrc"]);
    expect(existsSync(join(result.backupDir, ".zshrc"))).toBe(true);
    expect(existsSync(join(result.backupDir, ".bashrc"))).toBe(true);
    expect(readFileSync(join(result.backupDir, "manifest.json"), "utf-8")).toContain('"reason": "setup"');
  });

  test("writeZshrc uses omz template when pluginManager is omz", async () => {
    await writeZshrc("omz", { home: sandbox.path });

    const content = readFileSync(join(sandbox.path, ".zshrc"), "utf-8");
    expect(content).toContain("oh-my-zsh");
  });
});

describe("aliases step", () => {
  let sandbox;

  beforeEach(() => {
    vi.clearAllMocks();
    sandbox = createSandbox();
  });

  afterEach(() => {
    sandbox.cleanup();
  });

  test("writes aliases file in empty sandbox", async () => {
    await setupAliases({ home: sandbox.path });

    expect(existsSync(join(sandbox.path, ".config", "suitup", "aliases"))).toBe(true);
  });

  test("skips when aliases file already exists", async () => {
    mkdirSync(join(sandbox.path, ".config", "suitup"), { recursive: true });
    writeFileSync(join(sandbox.path, ".config", "suitup", "aliases"), "# my aliases", "utf-8");

    await setupAliases({ home: sandbox.path });

    const content = readFileSync(join(sandbox.path, ".config", "suitup", "aliases"), "utf-8");
    expect(content).toBe("# my aliases");
  });
});

describe("vim step", () => {
  let sandbox;

  beforeEach(() => {
    vi.clearAllMocks();
    sandbox = createSandbox();
  });

  afterEach(() => {
    sandbox.cleanup();
  });

  test("writes vim config and .vimrc in empty sandbox", async () => {
    await setupVim({ home: sandbox.path });

    expect(existsSync(join(sandbox.path, ".config", "suitup", "config.vim"))).toBe(true);
    expect(existsSync(join(sandbox.path, ".vimrc"))).toBe(true);

    const vimrc = readFileSync(join(sandbox.path, ".vimrc"), "utf-8");
    expect(vimrc).toContain("source");
    expect(vimrc).toContain("config.vim");
  });

  test("skips vim config when already exists", async () => {
    mkdirSync(join(sandbox.path, ".config", "suitup"), { recursive: true });
    writeFileSync(join(sandbox.path, ".config", "suitup", "config.vim"), "\" my vim config", "utf-8");

    await setupVim({ home: sandbox.path });

    const content = readFileSync(join(sandbox.path, ".config", "suitup", "config.vim"), "utf-8");
    expect(content).toBe("\" my vim config");
  });

  test("does not duplicate .vimrc source line on second run", async () => {
    await setupVim({ home: sandbox.path });
    await setupVim({ home: sandbox.path });

    const vimrc = readFileSync(join(sandbox.path, ".vimrc"), "utf-8");
    const sourceLines = vimrc.split("\n").filter((l) => l.includes("source"));
    expect(sourceLines.length).toBe(1);
  });
});
