import * as p from "@clack/prompts";
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { copyFile, copyIfNotExists, ensureDir, writeIfNotExists, readFileSafe, writeFile } from "../utils/fs.js";
import { CONFIGS_DIR } from "../constants.js";

/**
 * Create the ~/.config/zsh/ directory structure with all config files.
 * @param {object} [opts]
 * @param {string} [opts.home] - override home directory (for testing)
 */
export async function setupZshConfig({ home } = {}) {
  const base = home || homedir();
  const zshConfig = join(base, ".config", "zsh");
  const suitupConfig = join(base, ".config", "suitup");

  // Ensure directories
  for (const sub of ["core", "shared", "local"]) {
    ensureDir(join(zshConfig, sub));
  }
  ensureDir(suitupConfig);

  // Copy core configs (skip if already exist)
  const coreFiles = ["perf.zsh", "env.zsh", "paths.zsh", "options.zsh"];
  for (const file of coreFiles) {
    const copied = copyIfNotExists(join(CONFIGS_DIR, "core", file), join(zshConfig, "core", file));
    if (!copied) p.log.info(`Skipped core/${file} (already exists)`);
  }

  // Copy shared configs (skip if already exist)
  const sharedFiles = ["tools.zsh", "prompt.zsh"];
  for (const file of sharedFiles) {
    const copied = copyIfNotExists(join(CONFIGS_DIR, "shared", file), join(zshConfig, "shared", file));
    if (!copied) p.log.info(`Skipped shared/${file} (already exists)`);
  }

  // Create local placeholder (don't overwrite existing)
  writeIfNotExists(
    join(zshConfig, "local", "machine.zsh"),
    readFileSafe(join(CONFIGS_DIR, "local", "machine.zsh"))
  );

  p.log.success("Zsh config structure created at ~/.config/zsh/");
}

/**
 * Write the .zshrc file from template.
 * @param {"zinit" | "omz"} pluginManager
 * @param {object} [opts]
 * @param {string} [opts.home] - override home directory (for testing)
 */
export async function writeZshrc(pluginManager = "zinit", { home } = {}) {
  const base = home || homedir();
  const zshrc = join(base, ".zshrc");
  const templateName =
    pluginManager === "omz" ? "zshrc-omz.template" : "zshrc.template";
  const template = readFileSafe(join(CONFIGS_DIR, templateName));

  if (existsSync(zshrc)) {
    const existing = readFileSafe(zshrc);
    if (existing.includes("Generated by suitup")) {
      // Already a suitup-managed zshrc, overwrite
      writeFile(zshrc, template);
      p.log.success(".zshrc updated (suitup-managed)");
      return;
    }

    // Existing non-suitup zshrc — ask before overwriting
    const shouldOverwrite = await p.confirm({
      message: "~/.zshrc exists and is not managed by suitup. Overwrite? (backup will be created)",
      initialValue: false,
    });

    if (p.isCancel(shouldOverwrite) || !shouldOverwrite) {
      p.log.warn(".zshrc left unchanged. Use 'append' mode to add configs to your existing .zshrc.");
      return;
    }

    const backup = `${zshrc}.backup.${Date.now()}`;
    const { default: fs } = await import("node:fs");
    fs.copyFileSync(zshrc, backup);
    writeFile(zshrc, template);
    p.log.success(`.zshrc written (backup saved to ${backup})`);
  } else {
    writeFile(zshrc, template);
    p.log.success(".zshrc created");
  }
}
