import * as p from "@clack/prompts";
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { copyFile, copyIfNotExists, ensureDir, writeIfNotExists, readFileSafe, writeFile } from "../utils/fs.js";
import { CONFIGS_DIR } from "../constants.js";

const SHELL_RC_FILES = [
  ".zshrc",
  ".zprofile",
  ".zshenv",
  ".zlogin",
  ".bashrc",
  ".bash_profile",
  ".profile",
];

function createBackupStamp() {
  return new Date().toISOString().replace(/[:.]/g, "-");
}

export async function backupShellRcFiles({ home, reason = "setup" } = {}) {
  const base = home || homedir();
  const existingFiles = SHELL_RC_FILES.filter((file) => existsSync(join(base, file)));

  if (existingFiles.length === 0) {
    return null;
  }

  const backupDir = join(base, ".config", "suitup", "backups", `${createBackupStamp()}-${reason}`);
  ensureDir(backupDir);

  for (const file of existingFiles) {
    copyFile(join(base, file), join(backupDir, file));
  }

  const manifest = {
    createdAt: new Date().toISOString(),
    reason,
    files: existingFiles,
  };

  writeFile(join(backupDir, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
  return { backupDir, files: existingFiles };
}

/**
 * Create the ~/.config/zsh/ directory structure with all config files.
 * @param {object} [opts]
 * @param {string} [opts.home] - override home directory (for testing)
 * @param {"p10k" | "basic"} [opts.promptTheme] - prompt preset to install
 */
export async function setupZshConfig({ home, promptTheme = "p10k" } = {}) {
  const base = home || homedir();
  const zshConfig = join(base, ".config", "zsh");
  const suitupConfig = join(base, ".config", "suitup");

  // Ensure directories
  for (const sub of ["core", "shared", "local"]) {
    ensureDir(join(zshConfig, sub));
  }
  ensureDir(suitupConfig);

  // Copy core configs (skip if already exist)
  const coreFiles = ["perf.zsh", "env.zsh", "paths.zsh", "options.zsh"];
  for (const file of coreFiles) {
    const copied = copyIfNotExists(join(CONFIGS_DIR, "core", file), join(zshConfig, "core", file));
    if (!copied) p.log.info(`Skipped core/${file} (already exists)`);
  }

  // Copy shared configs (skip if already exist)
  const sharedFiles = ["tools.zsh", "fzf.zsh"];
  for (const file of sharedFiles) {
    const copied = copyIfNotExists(join(CONFIGS_DIR, "shared", file), join(zshConfig, "shared", file));
    if (!copied) p.log.info(`Skipped shared/${file} (already exists)`);
  }

  const promptSource = promptTheme === "basic" ? "prompt-basic.zsh" : "prompt.zsh";
  const promptDest = join(zshConfig, "shared", "prompt.zsh");
  const existingPrompt = readFileSafe(promptDest);
  if (!existingPrompt || existingPrompt.includes("Generated by suitup")) {
    copyFile(join(CONFIGS_DIR, "shared", promptSource), promptDest);
  } else {
    p.log.info("Skipped shared/prompt.zsh (already exists)");
  }

  // Create local placeholder (don't overwrite existing)
  writeIfNotExists(
    join(zshConfig, "local", "machine.zsh"),
    readFileSafe(join(CONFIGS_DIR, "local", "machine.zsh"))
  );

  p.log.success("Zsh config structure created at ~/.config/zsh/");
}

/**
 * Write the .zshrc file from template.
 * @param {"zinit" | "omz"} pluginManager
 * @param {object} [opts]
 * @param {string} [opts.home] - override home directory (for testing)
 */
export async function writeZshrc(pluginManager = "zinit", { home } = {}) {
  const base = home || homedir();
  const zshrc = join(base, ".zshrc");
  const templateName =
    pluginManager === "omz" ? "zshrc-omz.template" : "zshrc.template";
  const template = readFileSafe(join(CONFIGS_DIR, templateName));
  const shellBackup = await backupShellRcFiles({ home: base, reason: "setup" });

  if (shellBackup) {
    p.log.info(`Shell backups saved to ${shellBackup.backupDir.replace(base, "~")}`);
  }

  if (existsSync(zshrc)) {
    const existing = readFileSafe(zshrc);
    if (existing.includes("Generated by suitup")) {
      // Already a suitup-managed zshrc, overwrite
      writeFile(zshrc, template);
      p.log.success(".zshrc updated (suitup-managed)");
      return;
    }

    // Existing non-suitup zshrc — ask before overwriting
    const shouldOverwrite = await p.confirm({
      message: "~/.zshrc exists and is not managed by suitup. Overwrite? (backup will be created)",
      initialValue: false,
    });

    if (p.isCancel(shouldOverwrite) || !shouldOverwrite) {
      p.log.warn(".zshrc left unchanged. Use 'append' mode to add configs to your existing .zshrc.");
      return;
    }

    writeFile(zshrc, template);
    p.log.success(".zshrc written (backup saved under ~/.config/suitup/backups/)");
  } else {
    writeFile(zshrc, template);
    p.log.success(".zshrc created");
  }
}
