# Split creation
keybind = "super+d=new_split:right"
keybind = "super+shift+d=new_split:down"

# Split navigation
keybind = "super+alt+up=goto_split:up"
keybind = "super+alt+down=goto_split:down"
keybind = "super+alt+left=goto_split:left"
keybind = "super+alt+right=goto_split:right"

# Close the current split
keybind = "super+w=close_surface"
