import * as p from "@clack/prompts";
import pc from "picocolors";
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { readFileSafe, writeFile, copyFile } from "./fs.js";

function splitContent(content) {
  const normalized = content.replace(/\r\n/g, "\n");
  if (normalized.endsWith("\n")) {
    return normalized.slice(0, -1).split("\n");
  }
  return normalized.length > 0 ? normalized.split("\n") : [];
}

function joinContent(lines, preferFinalNewline = true) {
  const content = lines.join("\n");
  return preferFinalNewline ? `${content}\n` : content;
}

function getLcsPairs(left, right) {
  const dp = Array.from({ length: left.length + 1 }, () => Array(right.length + 1).fill(0));

  for (let i = left.length - 1; i >= 0; i--) {
    for (let j = right.length - 1; j >= 0; j--) {
      dp[i][j] = left[i] === right[j]
        ? dp[i + 1][j + 1] + 1
        : Math.max(dp[i + 1][j], dp[i][j + 1]);
    }
  }

  const pairs = [];
  let i = 0;
  let j = 0;
  while (i < left.length && j < right.length) {
    if (left[i] === right[j]) {
      pairs.push([i, j]);
      i++;
      j++;
    } else if (dp[i + 1][j] >= dp[i][j + 1]) {
      i++;
    } else {
      j++;
    }
  }
  return pairs;
}

export function mergeLineAdditions(existingContent, shippedContent) {
  if (existingContent === shippedContent) {
    return existingContent;
  }

  const existingLines = splitContent(existingContent);
  const shippedLines = splitContent(shippedContent);
  const pairs = getLcsPairs(shippedLines, existingLines);
  const merged = [];
  let shippedCursor = 0;
  let existingCursor = 0;

  for (const [shippedIndex, existingIndex] of pairs) {
    while (shippedCursor < shippedIndex) {
      merged.push(shippedLines[shippedCursor]);
      shippedCursor++;
    }

    while (existingCursor <= existingIndex) {
      merged.push(existingLines[existingCursor]);
      existingCursor++;
    }

    shippedCursor = shippedIndex + 1;
  }

  while (existingCursor < existingLines.length) {
    merged.push(existingLines[existingCursor]);
    existingCursor++;
  }

  while (shippedCursor < shippedLines.length) {
    merged.push(shippedLines[shippedCursor]);
    shippedCursor++;
  }

  return joinContent(merged, existingContent.endsWith("\n") || shippedContent.endsWith("\n"));
}

export function renderUnifiedDiff(beforeContent, afterContent, { from = "current", to = "proposed" } = {}) {
  const beforeLines = splitContent(beforeContent);
  const afterLines = splitContent(afterContent);
  const pairs = getLcsPairs(beforeLines, afterLines);
  const diff = [pc.dim(`--- ${from}`), pc.dim(`+++ ${to}`)];
  let beforeCursor = 0;
  let afterCursor = 0;

  for (const [beforeIndex, afterIndex] of pairs) {
    while (beforeCursor < beforeIndex) {
      diff.push(pc.red(`- ${beforeLines[beforeCursor]}`));
      beforeCursor++;
    }
    while (afterCursor < afterIndex) {
      diff.push(pc.green(`+ ${afterLines[afterCursor]}`));
      afterCursor++;
    }
    diff.push(`  ${beforeLines[beforeIndex]}`);
    beforeCursor = beforeIndex + 1;
    afterCursor = afterIndex + 1;
  }

  while (beforeCursor < beforeLines.length) {
    diff.push(pc.red(`- ${beforeLines[beforeCursor]}`));
    beforeCursor++;
  }
  while (afterCursor < afterLines.length) {
    diff.push(pc.green(`+ ${afterLines[afterCursor]}`));
    afterCursor++;
  }

  return diff.join("\n");
}

export function displayPath(filePath, home = homedir()) {
  return filePath.startsWith(home) ? `~${filePath.slice(home.length)}` : filePath;
}

export function isSuitupManagedConfig(content) {
  return content.includes("Generated by suitup") || content.includes("# >>> suitup/");
}

export async function applyManagedConfigUpdate({
  source,
  dest,
  label,
  unsupportedReason = "existing file is not marked as suitup-managed, so suitup cannot safely distinguish shipped lines from user-owned config",
  confirm = true,
  home = homedir(),
} = {}) {
  if (!existsSync(dest)) {
    copyFile(source, dest);
    p.log.success(`${label} written`);
    return { changed: true, reason: "created" };
  }

  const existing = readFileSafe(dest);
  const shipped = readFileSafe(source);
  if (existing === shipped) {
    p.log.info(`${label} is already up to date`);
    return { changed: false, reason: "unchanged" };
  }

  if (!isSuitupManagedConfig(existing)) {
    p.log.info(`Skipped ${label}: ${unsupportedReason}.`);
    return { changed: false, reason: "unsupported" };
  }

  const merged = mergeLineAdditions(existing, shipped);
  if (merged === existing) {
    p.log.info(`${label} has no safe line additions to apply`);
    return { changed: false, reason: "no-safe-additions" };
  }

  const shownPath = displayPath(dest, home);
  p.log.info(`Previewing suitup additions for ${shownPath}:\n${renderUnifiedDiff(existing, merged, { from: `${shownPath} current`, to: `${shownPath} proposed` })}`);

  if (confirm) {
    const shouldApply = await p.confirm({
      message: `Apply the previewed suitup additions to ${shownPath}?`,
      initialValue: true,
    });

    if (p.isCancel(shouldApply) || !shouldApply) {
      p.log.warn(`Skipped ${label}; user changes were preserved.`);
      return { changed: false, reason: "declined" };
    }
  }

  writeFile(dest, merged);
  p.log.success(`${label} updated`);
  return { changed: true, reason: "updated" };
}
