import * as p from "@clack/prompts";
import pc from "picocolors";
import { existsSync, readdirSync, rmSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { CONFIGS_DIR } from "./constants.js";
import { readFileSafe, writeFile } from "./utils/fs.js";

const SUITUP_HEADER = "Generated by suitup";
const SUITUP_BLOCK_RE = /^# >>> suitup\/[^\n]+ >>>\n[\s\S]*?^# <<< suitup\/[^\n]+ <<<\n?/gm;

const MANAGED_FILES = [
  { path: ".config/zsh/core/perf.zsh", templates: [join(CONFIGS_DIR, "core", "perf.zsh")] },
  { path: ".config/zsh/core/env.zsh", templates: [join(CONFIGS_DIR, "core", "env.zsh")] },
  { path: ".config/zsh/core/paths.zsh", templates: [join(CONFIGS_DIR, "core", "paths.zsh")] },
  { path: ".config/zsh/core/options.zsh", templates: [join(CONFIGS_DIR, "core", "options.zsh")] },
  { path: ".config/zsh/shared/tools.zsh", templates: [join(CONFIGS_DIR, "shared", "tools.zsh")] },
  { path: ".config/zsh/shared/fzf.zsh", templates: [join(CONFIGS_DIR, "shared", "fzf.zsh")] },
  { path: ".config/zsh/shared/completion.zsh", templates: [join(CONFIGS_DIR, "shared", "completion.zsh")] },
  { path: ".config/zsh/shared/highlighting.zsh", templates: [join(CONFIGS_DIR, "shared", "highlighting.zsh")] },
  { path: ".config/zsh/shared/plugins.zsh", templates: [join(CONFIGS_DIR, "shared", "plugins.zsh")] },
  { path: ".config/zsh/shared/aliases.zsh", templates: [join(CONFIGS_DIR, "shared", "aliases.zsh")] },
  {
    path: ".config/zsh/shared/prompt.zsh",
    templates: [
      join(CONFIGS_DIR, "shared", "prompt.zsh"),
      join(CONFIGS_DIR, "shared", "prompt-basic.zsh"),
    ],
  },
  { path: ".config/zsh/local/machine.zsh", templates: [join(CONFIGS_DIR, "local", "machine.zsh")] },
  { path: ".config/suitup/aliases", templates: [join(CONFIGS_DIR, "aliases")] },
  { path: ".config/suitup/zinit-plugins", templates: [join(CONFIGS_DIR, "zinit-plugins")] },
  { path: ".config/suitup/config.vim", templates: [join(CONFIGS_DIR, "config.vim")] },
];

function displayPath(base, relativePath) {
  return join(base, relativePath).replace(base, "~");
}

function isSuitupManaged(content) {
  return content.includes(SUITUP_HEADER);
}

function matchesManagedTemplate(fullPath, templates) {
  const content = readFileSafe(fullPath);
  return templates.some((templatePath) => content === readFileSafe(templatePath));
}

function listBackupDirs(base) {
  const backupRoot = join(base, ".config", "suitup", "backups");
  if (!existsSync(backupRoot)) {
    return [];
  }

  return readdirSync(backupRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => join(backupRoot, entry.name))
    .sort()
    .reverse();
}

function findRestorableBackup(base, relativePath) {
  for (const backupDir of listBackupDirs(base)) {
    const backupFile = join(backupDir, relativePath);
    if (!existsSync(backupFile)) {
      continue;
    }

    const content = readFileSafe(backupFile);
    if (!isSuitupManaged(content)) {
      return content;
    }
  }

  return "";
}

function stripSuitupBlocks(content) {
  const cleaned = content
    .replace(SUITUP_BLOCK_RE, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  return cleaned ? `${cleaned}\n` : "";
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function pruneEmptyDirs(base, directories) {
  for (const relativePath of directories) {
    const fullPath = join(base, relativePath);
    if (!existsSync(fullPath)) {
      continue;
    }

    try {
      if (readdirSync(fullPath).length === 0) {
        rmSync(fullPath, { recursive: true, force: true });
      }
    } catch {
      // Path is not a removable empty directory; keep it.
    }
  }
}

function restoreOrRemoveManagedRcFile(base, relativePath, summary) {
  const fullPath = join(base, relativePath);
  if (!existsSync(fullPath)) {
    return;
  }

  const backupContent = findRestorableBackup(base, relativePath);
  if (backupContent) {
    writeFile(fullPath, backupContent);
    summary.restored.push(displayPath(base, relativePath));
    return;
  }

  rmSync(fullPath, { force: true });
  summary.removed.push(displayPath(base, relativePath));
}

function cleanZshrc(base, summary) {
  const relativePath = ".zshrc";
  const fullPath = join(base, relativePath);
  if (!existsSync(fullPath)) {
    return;
  }

  const content = readFileSafe(fullPath);
  if (isSuitupManaged(content)) {
    restoreOrRemoveManagedRcFile(base, relativePath, summary);
    return;
  }

  const cleaned = stripSuitupBlocks(content);
  if (cleaned === content) {
    return;
  }

  if (cleaned) {
    writeFile(fullPath, cleaned);
    summary.cleaned.push(displayPath(base, relativePath));
    return;
  }

  rmSync(fullPath, { force: true });
  summary.removed.push(displayPath(base, relativePath));
}

function cleanZshenv(base, summary) {
  const relativePath = ".zshenv";
  const fullPath = join(base, relativePath);
  if (!existsSync(fullPath)) {
    return;
  }

  const content = readFileSafe(fullPath);
  if (!isSuitupManaged(content)) {
    summary.preserved.push(displayPath(base, relativePath));
    return;
  }

  restoreOrRemoveManagedRcFile(base, relativePath, summary);
}

function cleanVimrc(base, summary) {
  const vimrc = join(base, ".vimrc");
  if (!existsSync(vimrc)) {
    return;
  }

  const suitupVimConfig = join(base, ".config", "suitup", "config.vim");
  const content = readFileSafe(vimrc);
  const cleaned = content
    .replace(new RegExp(`^source ${escapeRegExp(suitupVimConfig)}\\s*\\n?`, "m"), "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  if (cleaned === content.trim()) {
    return;
  }

  if (cleaned) {
    writeFile(vimrc, `${cleaned}\n`);
    summary.cleaned.push("~/.vimrc");
    return;
  }

  rmSync(vimrc, { force: true });
  summary.removed.push("~/.vimrc");
}

function cleanManagedFiles(base, summary) {
  for (const managedFile of MANAGED_FILES) {
    const fullPath = join(base, managedFile.path);
    if (!existsSync(fullPath)) {
      continue;
    }

    if (matchesManagedTemplate(fullPath, managedFile.templates)) {
      rmSync(fullPath, { force: true });
      summary.removed.push(displayPath(base, managedFile.path));
    } else {
      summary.preserved.push(displayPath(base, managedFile.path));
    }
  }
}

export function cleanSandbox(base) {
  const summary = {
    restored: [],
    cleaned: [],
    removed: [],
    preserved: [],
  };

  cleanZshrc(base, summary);
  cleanZshenv(base, summary);
  cleanVimrc(base, summary);
  cleanManagedFiles(base, summary);

  const backupsRoot = join(base, ".config", "suitup", "backups");
  if (existsSync(backupsRoot)) {
    rmSync(backupsRoot, { recursive: true, force: true });
  }

  const dirsToPrune = Array.from(
    new Set(
      MANAGED_FILES
        .map((managedFile) => dirname(managedFile.path))
        .concat([".config/zsh/local", ".config/zsh/shared", ".config/zsh/core", ".config/zsh", ".config/suitup"])
    )
  ).sort((left, right) => right.length - left.length);

  pruneEmptyDirs(base, dirsToPrune);
  return summary;
}

/**
 * Clean up suitup-managed configurations.
 * @param {object} [opts]
 * @param {string} [opts.home] - override home directory (for testing)
 * @param {boolean} [opts.force] - skip interactive confirmation
 */
export async function runClean(opts = {}) {
  const base = opts.home || homedir();

  p.intro(pc.bgRed(pc.white(" Suit up! — Clean ")));

  if (!opts.force) {
    const confirm = await p.confirm({
      message: "This will remove suitup-managed config files and restore backups when available. Continue?",
      initialValue: false,
    });

    if (p.isCancel(confirm) || !confirm) {
      p.cancel("Clean cancelled.");
      return null;
    }
  }

  const summary = cleanSandbox(base);

  for (const restored of summary.restored) {
    p.log.success(`Restored ${restored} from backup`);
  }
  for (const cleaned of summary.cleaned) {
    p.log.success(`Removed suitup-managed blocks from ${cleaned}`);
  }
  for (const removed of summary.removed) {
    p.log.success(`Removed ${removed}`);
  }
  for (const preserved of summary.preserved) {
    p.log.info(`Preserved ${preserved} (user-modified)`);
  }

  if (
    summary.restored.length === 0 &&
    summary.cleaned.length === 0 &&
    summary.removed.length === 0 &&
    summary.preserved.length === 0
  ) {
    p.log.info("No suitup-managed files were found.");
  }

  p.outro("Clean complete.");
  return summary;
}
