import * as p from "@clack/prompts";
import pc from "picocolors";
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { bootstrap } from "./steps/bootstrap.js";
import { installZinit } from "./steps/plugin-manager.js";
import { CLI_TOOLS, installCliTools } from "./steps/cli-tools.js";
import { APPS, installApps } from "./steps/apps.js";
import { installFrontendTools } from "./steps/frontend.js";
import { setupSsh } from "./steps/ssh.js";
import { setupVim } from "./steps/vim.js";
import { setupAliases } from "./steps/aliases.js";
import { cleanDock } from "./steps/dock.js";
import { setupZshConfig, writeZshrc, writeZshenv } from "./steps/zsh-config.js";
import { readFileSafe } from "./utils/fs.js";
import { commandExists } from "./utils/shell.js";
import { isZshShell } from "./utils/shell-context.js";
export { isZshShell } from "./utils/shell-context.js";

export const SUITUP_PIXEL_LOGO = [
  "gddwwddwwddg",
  "gddwwwwwwddg",
  "ggdwwdwwddgg",
  "ggdwwrwwddgg",
  "ggdwrwrwddgg",
  "ggdwwrwwddgg",
  "ggdwrwrwddgg",
  "gggdwwrwddgg",
  "gggdwrpppwgg",
  "gggdrrpppwgs",
  "gggddrpppwgg",
];

function colorize256(code, text) {
  return `\x1b[38;5;${code}m${text}\x1b[0m`;
}

function renderPixel(pixel) {
  switch (pixel) {
    case "g":
      return colorize256(245, "██");
    case "d":
      return colorize256(236, "██");
    case "w":
      return colorize256(255, "██");
    case "r":
      return colorize256(202, "██");
    case "p":
      return colorize256(224, "██");
    case "s":
      return colorize256(255, "● ");
    default:
      return "  ";
  }
}

export function getWelcomeLogo() {
  const renderRow = (row) => [...row].map(renderPixel).join("");
  return SUITUP_PIXEL_LOGO.map(renderRow).join("\n");
}

export function getWelcomeMessage() {
  return `${getWelcomeLogo()}\n${pc.bgCyan(pc.black(" Suit up! "))}`;
}

export function getRecommendedCliToolValues() {
  return [...CLI_TOOLS.essentials, ...CLI_TOOLS.shell].map((tool) => tool.value);
}

export function getRecommendedAppValues() {
  return APPS.recommended.map((app) => app.value);
}

/**
 * Full interactive setup flow.
 */
export function getDefaultSteps(platform = process.platform) {
  return [
    "bootstrap",
    "zsh-config",
    "plugins",
    "cli-tools",
    ...(platform === "linux" ? [] : ["apps"]),
    "frontend",
    "aliases",
  ];
}

function hasCompletedBootstrap(platform, commandExistsFn) {
  if (!commandExistsFn("zsh")) {
    return false;
  }

  if (platform === "darwin") {
    return commandExistsFn("brew");
  }

  if (platform === "linux") {
    return ["apt-get", "dnf", "yum", "brew"].some((manager) => commandExistsFn(manager));
  }

  return false;
}

export function detectCompletedSteps({
  home = homedir(),
  platform = process.platform,
  commandExistsFn = commandExists,
} = {}) {
  const completed = new Set();
  const zshConfigDir = join(home, ".config", "zsh");
  const xdgDataHome = process.env.XDG_DATA_HOME || join(home, ".local", "share");
  const zinitHome = join(xdgDataHome, "zinit", "zinit.git");
  const zshrc = readFileSafe(join(home, ".zshrc"));
  const zshenv = readFileSafe(join(home, ".zshenv"));
  const vimrc = readFileSafe(join(home, ".vimrc"));

  if (hasCompletedBootstrap(platform, commandExistsFn)) {
    completed.add("bootstrap");
  }

  if (
    zshrc.includes("Generated by suitup") &&
    zshenv.includes("Generated by suitup") &&
    existsSync(join(zshConfigDir, "core", "perf.zsh")) &&
    existsSync(join(zshConfigDir, "core", "env.zsh")) &&
    existsSync(join(zshConfigDir, "core", "paths.zsh")) &&
    existsSync(join(zshConfigDir, "core", "options.zsh")) &&
    existsSync(join(zshConfigDir, "shared", "tools.zsh")) &&
    existsSync(join(zshConfigDir, "shared", "tools", "_loader.zsh")) &&
    existsSync(join(zshConfigDir, "shared", "completion.zsh")) &&
    existsSync(join(zshConfigDir, "shared", "highlighting.zsh")) &&
    existsSync(join(zshConfigDir, "shared", "prompt.zsh")) &&
    existsSync(join(zshConfigDir, "local", "machine.zsh"))
  ) {
    completed.add("zsh-config");
  }

  if (existsSync(join(zshConfigDir, "shared", "plugins.zsh")) || existsSync(zinitHome)) {
    completed.add("plugins");
  }

  if (existsSync(join(zshConfigDir, "shared", "aliases.zsh"))) {
    completed.add("aliases");
  }

  if (
    commandExistsFn("fnm") &&
    commandExistsFn("node") &&
    commandExistsFn("pnpm") &&
    commandExistsFn("git-cz")
  ) {
    completed.add("frontend");
  }

  if (existsSync(join(home, ".ssh", "github_rsa"))) {
    completed.add("ssh");
  }

  if (existsSync(join(zshConfigDir, "local", "config.vim")) && vimrc.includes("config.vim")) {
    completed.add("vim");
  }

  return [...completed];
}

export function getInitialStepValues(opts = {}) {
  const completed = new Set(detectCompletedSteps(opts));
  return getDefaultSteps(opts.platform).filter((step) => !completed.has(step));
}

export async function runSetup({ defaults = false } = {}) {
  p.note(getWelcomeMessage(), "Welcome");

  if (!isZshShell()) {
    p.log.error("Suitup setup must be run from zsh.");
    p.log.info("Switch to zsh first: run `zsh` for this session or `chsh -s \"$(which zsh)\"` to make it your default shell.");
    p.outro("No changes made.");
    return;
  }

  // --- Step 1: Select setup steps ---
  const completedSteps = detectCompletedSteps();
  const initialValues = getInitialStepValues();
  if (completedSteps.length > 0) {
    p.log.info(`Deselected already configured steps: ${completedSteps.join(", ")}`);
  }

  const steps = defaults
    ? initialValues
    : await p.multiselect({
        message: "Select setup steps:",
        required: true,
        options: [
          { value: "bootstrap", label: "Bootstrap", hint: "Package manager + Zsh" },
          { value: "zsh-config", label: "Zsh Config Structure", hint: "~/.config/zsh/" },
          { value: "plugins", label: "Plugin Manager", hint: "recommended zinit or skip" },
          { value: "cli-tools", label: "CLI Tools", hint: "bat, eza, fzf, fd, zoxide, atuin..." },
          { value: "apps", label: "GUI Apps", hint: "iTerm2, Raycast, VS Code..." },
          { value: "frontend", label: "Frontend Tools", hint: "fnm, pnpm, git-cz" },
          { value: "aliases", label: "Shell Aliases", hint: "git, eza, fzf shortcuts" },
          { value: "ssh", label: "SSH Key", hint: "generate GitHub SSH key" },
          { value: "vim", label: "Vim Config", hint: "basic vim setup" },
          { value: "dock", label: "Dock Cleanup", hint: "clean macOS Dock" },
        ],
        initialValues,
      });

  if (!defaults && (p.isCancel(steps) || steps.length === 0)) {
    p.cancel("Setup cancelled.");
    process.exit(0);
  }

  if (defaults && steps.length === 0) {
    p.outro("Nothing to do.");
    return;
  }

  // --- Step 2: Plugin manager choice (if selected) ---
  let pluginManager = "zinit";
  if (!defaults && steps.includes("plugins")) {
    const pmChoice = await p.select({
      message: "Choose plugin manager setup:",
      options: [
        { value: "zinit", label: "zinit", hint: "recommended - lightweight, fast, enough for most setups" },
        { value: "skip", label: "Skip plugin manager", hint: "keep native zsh features only" },
      ],
      initialValue: "zinit",
    });
    if (p.isCancel(pmChoice)) {
      p.cancel("Setup cancelled.");
      process.exit(0);
    }
    pluginManager = pmChoice;
  }

  let promptTheme = "p10k";
  if (!defaults && (steps.includes("zsh-config") || steps.includes("plugins"))) {
    const promptChoice = await p.select({
      message: "Choose a prompt preset:",
      options: [
        {
          value: "p10k",
          label: "Powerlevel10k",
          hint: "recommended - async git status stays fast in large repositories",
        },
        {
          value: "basic",
          label: "Basic zsh prompt",
          hint: "no Powerlevel10k, simple and dependency-free",
        },
      ],
      initialValue: "p10k",
    });
  if (p.isCancel(promptChoice)) {
      p.cancel("Setup cancelled.");
      process.exit(0);
    }
    promptTheme = promptChoice;
  }

  const zinitHome = join(
    process.env.XDG_DATA_HOME || join(homedir(), ".local", "share"),
    "zinit",
    "zinit.git"
  );
  const willInstallZinit = steps.includes("plugins") && pluginManager === "zinit";
  if (promptTheme === "p10k" && !(willInstallZinit || existsSync(zinitHome))) {
    p.log.warn("Powerlevel10k needs zinit. Since zinit is not installed or selected, suitup falls back to the Basic prompt.");
    promptTheme = "basic";
  }

  // --- Step 3: CLI tool selection (if selected) ---
  let selectedTools = [];
  if (steps.includes("cli-tools")) {
    if (defaults) {
      selectedTools = getRecommendedCliToolValues();
    } else {
      const toolChoice = await p.groupMultiselect({
        message: "Select CLI tools to install:",
        required: true,
        options: {
          Essentials: CLI_TOOLS.essentials,
          "Shell Enhancement": CLI_TOOLS.shell,
          Optional: CLI_TOOLS.optional,
        },
      });
      if (p.isCancel(toolChoice)) {
        p.cancel("Setup cancelled.");
        process.exit(0);
      }
      selectedTools = toolChoice;
    }
  }

  // --- Step 4: App selection (if selected) ---
  let selectedApps = [];
  if (steps.includes("apps")) {
    if (defaults) {
      selectedApps = getRecommendedAppValues();
    } else {
      const appChoice = await p.groupMultiselect({
        message: "Select apps to install:",
        options: {
          Recommended: APPS.recommended,
          Optional: APPS.optional,
          Fonts: APPS.fonts,
        },
      });
      if (p.isCancel(appChoice)) {
        p.cancel("Setup cancelled.");
        process.exit(0);
      }
      selectedApps = appChoice;
    }
  }

  // --- Execute selected steps ---
  p.log.step(pc.bold("Starting installation..."));

  if (steps.includes("bootstrap")) {
    await bootstrap({ defaults });
  }

  if (steps.includes("zsh-config")) {
    await setupZshConfig({ promptTheme });
  }

  if (steps.includes("plugins")) {
    if (pluginManager === "zinit") {
      await installZinit();
    }
  }

  if (steps.includes("cli-tools")) {
    await installCliTools(selectedTools);
  }

  if (steps.includes("apps")) {
    await installApps(selectedApps);
  }

  if (steps.includes("frontend")) {
    await installFrontendTools();
  }

  if (steps.includes("aliases")) {
    await setupAliases();
  }

  if (steps.includes("ssh")) {
    await setupSsh();
  }

  if (steps.includes("vim")) {
    await setupVim();
  }

  if (steps.includes("dock")) {
    await cleanDock();
  }

  // --- Write .zshrc ---
  if (steps.includes("zsh-config")) {
    await writeZshrc(pluginManager);
    await writeZshenv();
  }

  if (promptTheme === "p10k" && !existsSync(join(homedir(), ".p10k.zsh"))) {
    if (defaults) {
      p.log.step("Launching Powerlevel10k configuration wizard...");
      spawnSync("zsh", ["-lc", "p10k configure"], { stdio: "inherit" });
    } else {
      p.log.info("Powerlevel10k is selected, but `~/.p10k.zsh` was not found. Suitup keeps a basic prompt until you run `p10k configure` in zsh, which avoids dropping you into an interactive wizard during setup.");
    }
  }

  p.outro(
    `Done! Run ${pc.cyan("exec zsh")} to reload your shell.\n` +
    `  Problems? ${pc.underline(pc.cyan("https://github.com/ChangeHow/suitup/issues"))}`
  );
}
